name: aetherra
description: Aetherra Army Creator

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  supabase_flutter: ^2.8.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  pdfx: ^2.8.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  url_launcher: ^6.3.0
  pdf: ^3.11.1
  printing: ^5.13.2
  share_plus: ^13.1.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logo.png